name: FactionTags
version: ${project.version}
main: net.lapismc.factiontags.FactionTags
depend: [Factions, MassiveCore]
authors: [dart2112]
commands:
  factiontags:
    description: Reload faction tags
